name: Tag on PR Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest commit message
        id: commit_msg
        run: |
          commit_msg="$(git log -1 --pretty=%B)"
          echo "msg<<EOF" >> $GITHUB_OUTPUT
          echo "$commit_msg" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check for PR merge
        if: contains(steps.commit_msg.outputs.msg, 'Merge pull request')
        run: echo "PR merge detected, creating tag."

      - name: Create tag
        if: contains(steps.commit_msg.outputs.msg, 'Merge pull request')
        run: |
          TAG="pr-merge-$(date +'%Y%m%d-%H%M%S')"
          git tag $TAG
          git push origin $TAG
